### ISSUE TITLE
[Question] What is *.wt

### ISSUE THREAD

**Issue by Sergei-Larin** [RD17/ambar#101]
Hi,
I had the files at /opt/ambar/db Collection-*.wt and Index-*.wt. Collections-*.wt are very much increased in size. What are these files and in what proportion they will grow, relative to the size of the shared folder?

And one more question:
Can the Ambar index files on user's computers from local network? E.g. \\user-pc1\c$, \\user-pc2\d$

**Comment by Sergei-Larin** [comment]
Also I would like know can the Ambar download searched results in file?

**Comment by sochix** [comment]
> What are these files and in what proportion they will grow, relative to the size of the shared folder?

@Jaseri it's mongodb storage. In mongodb Ambar stores extracted from files text and (if preserveOriginals options is `true` ) the original files. Extracted text size ~ 30% of original file size. So to sum up, if preserveOriginals is `false` then Ambar size will be ~ 30% of your share size, otherwise ~130%of your share size

> Can the Ambar index files on user's computers from local network? E.g. \user-pc1\c$, \user-pc2\d$

Yes, take a look at [SMB crawler in our blog](https://blog.ambar.cloud/advanced-ambar-usage-crawling-your-own-shared-folders/)

> Also I would like know can the Ambar download searched results in file?

Do not understand the question

**Comment by Sergei-Larin** [comment]
Thank's for answers!
Try to rephrase my questioin:
If I found the files I needed. Can I unload it list at .txt or other type?

**Comment by sochix** [comment]
@Jaseri from ui not, but you can connect to our rest api and save the results to txt file
