### ISSUE TITLE
Can't Download File (File Content Not Found)

### ISSUE THREAD

**Issue by dkhd** [RD17/ambar#111]
Hi,

I managed to successfully run Ambar on my system. It works like a charm. Only, I cannot download the files using the API request (I use Google Chrome).

Here's the reference:
`GET http://ambar/api/files/:download_uri `

I tried on the `https://app.ambar.cloud/` and the method works fine, but it just don't work on mine. Instead, it shows this error message:

```
{
    "message": "File content not found"
}
```

How can this happen and how to solve it?

**Comment by noviceiii** [comment]
I had the same issue when
1. I ran the indexing service with preserveOriginals=false (for testing)
and then
2. enabled preserveOriginals=true 

This had the effect that all existing documents in ambar had their files missing.
Since I did install the server anyway again I had not to deal with it.

However, and if the above steps could be the cause, I would try the following ideas
a. change the file name of the original files so they got loaded again; re-index
b. touch the file; re-index
c. Create the Crawler again (Settings on the WebInterface -> Crawler)
...it is probably sufficient to just delete the UID

**Comment by sochix** [comment]
@noviceiii you should always use preserveOriginals=true to download files via API

**Comment by dkhd** [comment]
Hi all,

It works now. I can download the files by setting the `perserveOriginals=true` in the `config.json`.

Thank's for the help!

**Comment by ljgstudy** [comment]
@dkhd Could you tell me which config.json modified? Thanks in advance!

**Comment by itnoreplymax** [comment]
@dkhd Could you tell me which config.json modified? Thanks in advance..

**Comment by evandroabreu** [comment]
> Hi all,
> 
> It works now. I can download the files by setting the `perserveOriginals=true` in the `config.json`.
> 
> Thank's for the help!

Hello, please, where is config.json ?

**Comment by iliapir2** [comment]
@evandroabreu this setting was removed since Ambar v2. All files that uploaded via crawler can be downloaded from it's source (crawler will work as a proxy), files uploaded via UI can't be downloaded
