### ISSUE TITLE
Pipeline error End-of-File

### ISSUE THREAD

**Issue by bakrowork** [RD17/ambar#166]
Hi

I am running into the following error in the logs: 

```
[pipeline] [error] [0] error parsing //Docs/xxxxxxxx.pdf JVM exception occurred: Error: End-of-File, expected line
```
My docs are readable by everybody, I am running a ubuntu16.04 box with docker.

Where could I find more log about this error? Does somebody run into this error?

**Comment by bakrowork** [comment]
i should be something with read rights.
I just created a simple asd.txt file and I get the following error:
```GD_Docs/asd.txt JVM exception occurred: InputStream must have > 0 bytes```

**Comment by bakrowork** [comment]
If I am correct the last error is generated by this line:
https://github.com/apache/tika/blob/master/tika-core/src/main/java/org/apache/tika/parser/AutoDetectParser.java#L122

**Comment by evilham** [comment]
I am having the exact same issue :-D.

**Comment by evilham** [comment]
Solved!

By checking: `docker-compose logs`, I saw that there was a dns lookup error; then noticed that both @bakrowork and I had used something not-DNS valid as the name for the crawler.

I guess this was a docker-rookie mistake. It should be fixed with a mention in the `README` not to use weird stuff as the crawler name :-).

@bakrowork should now:
1. `docker-compose down`
2. `rm -rf $YOUR_DATA_DIR` (care not to delete your source data, but only ambar's data dir)
3. change `docker-compose.yml` so that the crawler name basically only contains lowercase ascii chars.
4. `docker-compose up -d`

**Comment by bakrowork** [comment]
Thank you @evilham

**Comment by AyKarsi** [comment]
@evilham could you maybe mention that the crawler name should be lower case in the installation guide? 
Could save people some hours debugging. (I'm glad I found this post eventually)

**Comment by evilham** [comment]
@AyKarsi I can't :-) but maybe @sochix can.

**Comment by sochix** [comment]
@AyKarsi @evilham it's already been in Installation guide, please read carefully

> Replace ```${crawlerName}``` with desired name for your crawler **(only lowercase latin letters and dashes are supported)**. Check that service block name and  crawler name are the same
