### ISSUE TITLE
Instruction: How to Build Up Ambar From Scratch

### ISSUE THREAD

**Issue by patrick4njos** [RD17/ambar#243]
Hello, 

I want to try "ambar search" but, when I do the command from the documentation 

`"docker-compose pull"`

I get this following error:

`"Get https://repo.ambar.cloud:443/v2/ambar-redis/manifests/2.1: no basic auth credentials" `

Is there a basic auth to be able to install from repository? 

I will appreciate if you could help me.

Thanks

**Comment by sochix** [comment]
Hello, 
this error occurs due to our new politics of docker images distribution.

In short, Ambar is open-source project and you can build docker images from scratch and modify docker-compose to make it work, or you can buy prebuilt Ambar images. 

[See pricing page for the further details](https://ambar.cloud/pricing/).

*P.S. I'll add this notice to the docs.*

**Comment by dareneiri** [comment]
Can you provide information of when you will have documentation on how to build the docker images from scratch?

**Comment by valeriob** [comment]
> Can you provide information of when you will have documentation on how to build the docker images from scratch?

+1 thanks !

**Comment by sochix** [comment]
@valeriob @dareneiri maybe we can ask help of community to do it?

**Comment by valeriob** [comment]
Sure, i was able to build it, when i find 15' i could prepare a script

**Comment by aaa-bbb111222** [comment]
> Sure, i was able to build it, when i find 15' i could prepare a script

@valeriob , 
So what about script?
