### ISSUE TITLE
FrontEnd dist is missing

### ISSUE THREAD

**Issue by Ulli2k** [RD17/ambar#247]
I am on the way to test Ambar and got an error during docker built process.
In the FrontEnd container the "dist" folder is missing.
I guess the reason is you have added this folder in your ".gitignore" file.

Could you add this in the repository, please?

**Comment by chazu** [comment]
@Ulli2k `dist` is populated by compiling the frontend project - assuming you've got an acceptable version of node (I used 8.1.3) installed, try `npm install` followed by `npm run compile`.

I did have to upgrade the version of `node-sass` referenced in the package.json to get the deps to install cleanly but otherwise it was pretty simple.

Good luck!

**Comment by sochix** [comment]
@chazu it would be awesome if you could write an instruction on how to build ambar-frontend. Check issue #243
